// products
export const products = [
  {
    name: 'Expresso Americano',
    image: 'coffeeAmericano',
    type: ['Tradicional'],
    label: 'Expresso diluído, menos intenso que o tradicional',
    price: '9,90',
    amount: 0,
  },
  {
    name: 'Mocaccino',
    image: 'coffeeMochaccino',
    type: ['Tradicional', 'Com Leite'],
    label: 'Café expresso com calda de chocolate, pouco leite e espuma',
    price: '9,90',
    amount: 0,
  },
  {
    name: 'Macchiato',
    image: 'coffeeMacchiato',
    type: ['Tradicional', 'Com Leite'],
    label: 'Café expresso misturado com um pouco de leite quente e espuma',
    price: '9,90',
    amount: 0,
  },
  {
    name: 'Latte',
    image: 'coffeeLatte',
    type: ['Tradicional', 'Com Leite'],
    label: 'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    price: '9,90',
    amount: 0,
  },
  {
    name: 'Irlandês',
    image: 'coffeeIrlandes',
    type: ['Especial', 'Alcoólico'],
    label: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    price: '9,90',
    amount: 0,
  },
  {
    name: 'Havaiano',
    image: 'coffeeHavaiano',
    type: ['Especial'],
    label: 'Bebida adocicada preparada com café e leite de coco',
    price: '9,90',
    amount: 0,
  },
  {
    name: 'Expresso Cremoso',
    image: 'coffeeExpressoCremoso',
    type: ['Tradicional'],
    label: 'Café expresso tradicional com espuma cremosa',
    price: '9,90',
    amount: 0,
  },
  {
    name: 'Expresso Tradicional',
    image: 'coffeeExpresso',
    type: ['Tradicional'],
    label: 'O tradicional café feito com água quente e grãos moídos',
    price: '9,90',
    amount: 0,
  },
  {
    name: 'Chocolate Quente',
    image: 'coffeeChocolateQuente',
    type: ['Especial', 'Com Leite'],
    label: 'Bebida feita com chocolate dissolvido no leite quente e café',
    price: '9,90',
    amount: 0,
  },
  {
    name: 'Capuccino',
    image: 'coffeeCapuccino',
    type: ['Especial', 'Com Leite'],
    label: 'Bebida com canela feita de doses iguais de café, leite e espuma',
    price: '9,90',
    amount: 0,
  },
  {
    name: 'Café Gelado',
    image: 'coffeeCafeGelado',
    type: ['Tradicional', 'Gelado'],
    label: 'Bebida preparada com café expresso e cubos de gelo',
    price: '9,90',
    amount: 0,
  },
  {
    name: 'Café com Leite',
    image: 'coffeeCafeComLeite',
    type: ['Tradicional', 'Com Leite'],
    label: 'Meio a meio de expresso tradicional com leite vaporizado',
    price: '9,90',
    amount: 0,
  },
  {
    name: 'Árabe',
    image: 'coffeeArabe',
    type: ['Especial'],
    label: 'Bebida preparada com grãos de café árabe e especiarias',
    price: '9,90',
    amount: 0,
  },
  {
    name: 'Cubano',
    image: 'coffeeCubano',
    type: ['Especial', 'Alcoólico', 'Gelado'],
    label: 'Drink gelado de café expresso com rum, creme de leite e hortelã',
    price: '9,90',
    amount: 0,
  },
]
